[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
